### ISSUE TITLE
Bertahap konversi ke laravel untuk rilis 22.07 - 22.08

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-pbb#9]
Rilis 22.07
- [x] 1. https://github.com/OpenSID/wiki-pbb/issues/22
- [x] 2. https://github.com/OpenSID/wiki-pbb/issues/23
- [x] 3. https://github.com/OpenSID/wiki-pbb/issues/24
- [x] 4. https://github.com/OpenSID/wiki-pbb/issues/25
- [x] 5. https://github.com/OpenSID/wiki-pbb/issues/26
- [x] 6. https://github.com/OpenSID/wiki-pbb/issues/27
- [x] 7. https://github.com/OpenSID/wiki-pbb/issues/29
- [x] 8. https://github.com/OpenSID/wiki-pbb/issues/30
- [x] 9. https://github.com/OpenSID/wiki-pbb/issues/31
- [x] 10. https://github.com/OpenSID/wiki-pbb/issues/32
- [x] 11. https://github.com/OpenSID/wiki-pbb/issues/33
- [x] 12. https://github.com/OpenSID/wiki-pbb/issues/52
- [x] 13. https://github.com/OpenSID/wiki-pbb/issues/53
- [x] 14. (https://github.com/OpenSID/wiki-pbb/issues/2) Periode
- [x] 15. (https://github.com/OpenSID/wiki-pbb/issues/37) Subjek Pajak
- [x] 16. (https://github.com/OpenSID/wiki-pbb/issues/43) Objek Pajak
- [x] 17. https://github.com/OpenSID/wiki-pbb/issues/46
- [x] 18. https://github.com/OpenSID/wiki-pbb/issues/49
- [x] 19. https://github.com/OpenSID/wiki-pbb/issues/51
 
Rilis 22.08
- [x] 1. https://github.com/OpenSID/wiki-pbb/issues/47
- [x] 2. https://github.com/OpenSID/wiki-pbb/issues/28
- [x] 3. https://github.com/OpenSID/wiki-pbb/issues/34
- [x] 4. (https://github.com/OpenSID/wiki-pbb/issues/20) Export / Import Excel

**Comment by scqolbu24** [comment]
Pada Target 22.08 proses konversi hanya terselesaian 1 issue dikarenakan ada yang lebih prioritas yaitu OpenSID Saas.
Target 22.09   
- [ ] 1. https://github.com/OpenSID/wiki-pbb/issues/28
- [x] 2. https://github.com/OpenSID/wiki-pbb/issues/34
- [ ] 3. (https://github.com/OpenSID/wiki-pbb/issues/20) Export / Import Excel

**Comment by scqolbu24** [comment]
Pada Target 22.09 proses konversi hanya terselesaian 1 issue dikarenakan ada yang lebih prioritas yaitu Layanan OpenSID Siap Pakai.
Target 22.10   
- [x] 1. https://github.com/OpenSID/wiki-pbb/issues/28
- [x] 2. (https://github.com/OpenSID/wiki-pbb/issues/20) Export / Import Excel
- [x] 3. https://github.com/OpenSID/wiki-pbb/issues/72

**Comment by scqolbu24** [comment]
Pada Target 22.10 proses konversi hanya terselesaian 2 issue dikarenakan ada yang lebih prioritas yaitu Layanan OpenSID Siap Pakai.
Target 22.11
- [x] 1. https://github.com/OpenSID/wiki-pbb/issues/28
